name: Tuğrul Gençoğlu
description: Karalıyorum bir şeyler...
meta_description: "Tuğrul Gençoğlu, kişisel blog"

markdown: kramdown
highlighter: rouge
future: true
logo: false
paginate: 15
baseurl: /
domain_name: "http://gencoglutugrul.com"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""

# Disqus config
disqus-shortname: ""
